# Generated by Django 5.2.4 on 2025-07-23 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_emergencyalert_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_type': 'victim'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
